<a href="https://colab.research.google.com/github/varun2068/Coversions/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello World")

Hello World


In [3]:
import sys
import numpy as np

In [4]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [5]:
a = np.array([1, 2, 3, 5, 4])

In [6]:
print(a[0])

1


To Find the Dimension of the array

In [10]:
a.ndim

1

To Find the size of array

In [11]:
a.size

5

In [12]:
a[1:3]

array([2, 3])

In [14]:
a[[1, 2, -1]]

array([2, 3, 4])

In [15]:
a.dtype

dtype('int64')

In [16]:
b = np.array([0.0, 1.0, 2.0, 3.0, 4.0])

In [17]:
b.dtype

dtype('float64')

# **Dimensions And Shape**

In [19]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])

In [20]:
A

array([[1, 2, 3],
       [4, 5, 6]])

To Find the shape of Array

In [21]:
A.shape

(2, 3)

Dimension of Array

In [22]:
A.ndim

2

In [23]:
A.size

6

##**3D Array**

In [25]:
B = np.array([
              [
               [12, 23, 34],
               [21, 32, 43],
              ],
              [
               [45, 56, 67],
               [76, 65, 54],
              ]
])

In [26]:
B.size

12

In [27]:
B.ndim

3

In [28]:
B.shape

(2, 2, 3)

In [29]:
B.dtype

dtype('int64')

#**Indexing And Slicing Of Matrices**

In [30]:
#Square Matrix
A = np.array([[1, 2, 3,],
             [4, 5, 6],
             [7, 8, 9]])

In [31]:
A


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
A[1]

array([4, 5, 6])

In [33]:
A[2]

array([7, 8, 9])

In [34]:
A[0]

array([1, 2, 3])

In [35]:
A[1,2]

6

In [36]:
A[1][2]

6

In [37]:
A[1] = np.array([10, 10, 10])

In [38]:
A[1]

array([10, 10, 10])

In [39]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [41]:
A[2] = 99

In [42]:
A[2]

array([99, 99, 99])

In [51]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [43]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

#**Summary Statistics**

In [44]:
A = np.array([
              [1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
])

In [45]:
A.sum()

45

In [46]:
A.mean()

5.0

In [47]:
#Variance
A.var()

6.666666666666667

In [48]:
#standard deviation
A.std()

2.581988897471611

In [49]:
# Sum of first Column
A.sum(axis=0)

array([12, 15, 18])

In [50]:
A.sum(axis=1)

array([ 6, 15, 24])

#**Broadcasting And Vectorized operations**

In [65]:
a = np.arange(4)

In [66]:
a

array([0, 1, 2, 3])

In [68]:
a + 10

array([10, 11, 12, 13])

In [69]:
a * 10


array([ 0, 10, 20, 30])

In [70]:
a == 100

array([False, False, False, False])

In [72]:
a

array([0, 1, 2, 3])

In [73]:
l = [0, 1, 2, 3, 4]

In [75]:
[i * 10 for i in l]

[0, 10, 20, 30, 40]

In [76]:
a = np.arange(4)

In [77]:
a

array([0, 1, 2, 3])

In [78]:
n = np.array([10, 10, 10, 10])

In [80]:
a + n

array([10, 11, 12, 13])

In [81]:
a * n

array([ 0, 10, 20, 30])

#**Boolean Arrays**

In [82]:
a = np.arange(4)

In [83]:
a

array([0, 1, 2, 3])

In [84]:
a[[0, -1]]

array([0, 3])

In [85]:
a[[True, False, False, True]]

array([0, 3])

In [86]:
a == 2

array([False, False,  True, False])

In [87]:
a == 1

array([False,  True, False, False])

In [88]:
a == 3

array([False, False, False,  True])

As in above the number 3 is present at last position that's why it show True else all False

In [89]:
a == 4

array([False, False, False, False])

In above code 4 is not present in arrays that's why the ouput is False all element.

In [90]:
a[a >= 2]

array([2, 3])

In [91]:
a.mean()

1.5

In [92]:
a[a> a.mean()]

array([2, 3])

In [95]:
a[~(a> a.mean())]

array([0, 1])

In [96]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [97]:
a[(a == 0)& (a == 1)]

array([], dtype=int64)

In [98]:
a[(a == 2) & (a % 2 == 0)]

array([2])

In [101]:
A = np.random.randint(100, size=(3, 3))

In [102]:
A

array([[67, 32,  0],
       [73,  8,  5],
       [77, 15, 36]])

In [105]:
A[np.array([
           [True, False, True,],
           [False, True, False],
           [True, False, True]
])]

array([67,  0,  8, 77, 36])

In [106]:
A > 30

array([[ True,  True, False],
       [ True, False, False],
       [ True, False,  True]])